/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pembayaran.nilai.kalkulator;

/**
 *
 * @author Hyung
 */
public class Pembayaran extends javax.swing.JFrame {

    /**
     * Creates new form Pembayaran
     */
    public Pembayaran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hb1 = new javax.swing.JTextField();
        hb2 = new javax.swing.JTextField();
        hb3 = new javax.swing.JTextField();
        proses = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        disc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 0));
        jPanel1.setLayout(null);

        jLabel1.setText("Harga Barang 1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 60, 90, 20);

        jLabel2.setText("Harga Barang 2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 100, 90, 20);

        jLabel3.setText("Harga Barang 3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 140, 90, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("PEMBAYARAN");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 10, 120, 17);
        jPanel1.add(hb1);
        hb1.setBounds(110, 50, 180, 30);
        jPanel1.add(hb2);
        hb2.setBounds(110, 90, 180, 30);
        jPanel1.add(hb3);
        hb3.setBounds(110, 130, 180, 30);

        proses.setText("Proses");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });
        jPanel1.add(proses);
        proses.setBounds(220, 210, 70, 30);

        jLabel5.setText("Diskon");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 180, 40, 20);
        jPanel1.add(disc);
        disc.setBounds(110, 170, 180, 30);

        hasil.setColumns(20);
        hasil.setRows(5);
        jScrollPane1.setViewportView(hasil);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 250, 280, 160);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 300, 420);

        setSize(new java.awt.Dimension(316, 460));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        // TODO add your handling code here:
        int one = Integer.parseInt(String.valueOf(hb1.getText()));
        int two = Integer.parseInt(String.valueOf(hb2.getText()));
        int three = Integer.parseInt(String.valueOf(hb3.getText()));
        int discount = Integer.parseInt(String.valueOf(disc.getText()));
        
        int cut = 100-discount;
        int total = one+two+three;
        int slip = total/100*cut;
        
        hasil.setText("Harga Barang 1 : Rp. "+one+",-" +
                      "\nHarga Barang 2 : Rp. "+two+",-" +
                      "\nHarga Barang 3 : Rp. "+three+",-" +
                      "\nTotal Harga : Rp. "+total+",-" +
                      "\n Diskon : "+discount+ "%" +
                      "\nTotal Pembayaran : Rp. "+slip+",-");
    }//GEN-LAST:event_prosesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Pembayaran().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField disc;
    private javax.swing.JTextArea hasil;
    private javax.swing.JTextField hb1;
    private javax.swing.JTextField hb2;
    private javax.swing.JTextField hb3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton proses;
    // End of variables declaration//GEN-END:variables
}
