/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pembayaran.nilai.kalkulator;

/**
 *
 * @author Hyung
 */
public class PenilaianSiswa extends javax.swing.JFrame {

    /**
     * Creates new form PenilaianSiswa
     */
    public PenilaianSiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        proses = new javax.swing.JButton();
        nama = new javax.swing.JTextField();
        absen = new javax.swing.JTextField();
        mapel = new javax.swing.JTextField();
        score = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        result = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Penilaian Siswa");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 10, 120, 20);

        jLabel2.setText("Nama");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 50, 50, 20);

        jLabel3.setText("Absen");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 90, 50, 20);

        jLabel4.setText("Mapel");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 130, 50, 20);

        jLabel5.setText("Nilai");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 170, 40, 20);

        proses.setText("Proses");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });
        jPanel1.add(proses);
        proses.setBounds(170, 200, 70, 30);
        jPanel1.add(nama);
        nama.setBounds(120, 40, 170, 30);
        jPanel1.add(absen);
        absen.setBounds(120, 80, 170, 30);
        jPanel1.add(mapel);
        mapel.setBounds(120, 120, 170, 30);
        jPanel1.add(score);
        score.setBounds(120, 160, 170, 30);

        result.setColumns(20);
        result.setRows(5);
        jScrollPane1.setViewportView(result);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 240, 280, 140);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 360, 390);

        setSize(new java.awt.Dimension(376, 430));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        // TODO add your handling code here:
        String name = nama.getText();
        String absent = absen.getText();
        String matpel = mapel.getText();
        int nilai = Integer.parseInt(String.valueOf(score.getText()));
        
        if (nilai < 75)
            result.setText("Nama: "+name+"\n"+"Absen : "+absent+"\n"+"Mata Pelajaran : "+matpel+"\n"+"Nilai : "+nilai+"\n"+"Gak lulus bro..");
        else if (nilai >= 75 && nilai <= 100)
            result.setText("Nama: "+name+"\n"+"Absen : "+absent+"\n"+"Mata Pelajaran : "+matpel+"\n"+"Nilai : "+nilai+"\n"+"Lulus weh, ntap djiwa");
        else if (nilai > 100)
            result.setText("Nama: "+name+"\n"+"Absen : "+absent+"\n"+"Mata Pelajaran : "+matpel+"\n"+"Nilai : "+nilai+"\n"+"Nilai tinggi amat nyong?");
        else if (nilai < 0)
            result.setText("Nama: "+name+"\n"+"Absen : "+absent+"\n"+"Mata Pelajaran : "+matpel+"\n"+"Nilai : "+nilai+"\n"+"Nilai kosong? Abis ngapain? Nabok guru? :v");
    }//GEN-LAST:event_prosesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenilaianSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenilaianSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenilaianSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenilaianSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PenilaianSiswa().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField absen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mapel;
    private javax.swing.JTextField nama;
    private javax.swing.JButton proses;
    private javax.swing.JTextArea result;
    private javax.swing.JTextField score;
    // End of variables declaration//GEN-END:variables
}
